version: "2"
services:
  app:
    image: jwuebblz/flask:latest
    restart: on-failure
    links:
      - db
    networks:
      - main-network
  db:
    image: jwuebblz/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: poop
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - main-network
  nginx:
    image: jwuebblz/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - main-network
volumes:
  mysql-data:
    driver: local
networks:
  main-network:
    driver: bridge
